# Generated by Django 4.2.3 on 2023-07-22 04:34

from django.db import migrations, models
import loanpro_api.constants


class Migration(migrations.Migration):
    dependencies = [
        ("loanpro_api", "0002_alter_customer_status_alter_loan_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "ACTIVE"), (2, "INACTIVE")],
                default=loanpro_api.constants.StatusForCustomer["ACTIVE"],
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.SmallIntegerField(
                choices=[(1, "PENDING"), (2, "ACTIVE"), (3, "REJECTED"), (4, "PAID")],
                default=loanpro_api.constants.StatusForLoan["PENDING"],
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.SmallIntegerField(choices=[(1, "COMPLETED"), (2, "REJECTED")]),
        ),
    ]
