# Generated by Django 4.2.3 on 2023-07-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loanpro_api", "0003_alter_customer_status_alter_loan_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="taken_at",
            field=models.DateTimeField(blank=True, default=None),
        ),
    ]
