# Generated by Django 4.2.3 on 2023-07-22 05:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("loanpro_api", "0004_alter_loan_taken_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="taken_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
