# Generated by Django 4.2.3 on 2023-07-23 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("loanpro_api", "0005_alter_loan_taken_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="customer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="loanpro_api.customer",
            ),
        ),
    ]
