# Generated by Django 4.2.3 on 2023-07-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("loanpro_api", "0006_alter_loan_customer_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="customer_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="loanpro_api.customer"
            ),
        ),
    ]
