# Generated by Django 4.2.3 on 2023-07-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loanpro_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="loan",
            name="status",
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.SmallIntegerField(),
        ),
    ]
